name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: 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
        store: lighthouse-ci-test.myshopify.com
        password: sultee
